spring.application.name=financial
spring.datasource.url=jdbc:sqlite:D:\\SQLiteStudio\\Market.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# 1. Configura o pool do Hikari para enviar comandos em UTF-8 para o driver JDBC
spring.datasource.hikari.connection-init-sql=PRAGMA encoding = 'UTF-8';

# 2. Garante que o Spring envie as respostas JSON do navegador em UTF-8
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
